[tox]
envlist=
    #docs,
;    py37-django{22,32}-fido11,
    py38-django{22,32,42}-fido11
    py39-django{22,32,42}-fido11
    py310-django{32,42,52}-fido{11,20,21}
    py311-django{42,52}-fido{11,20,21}
    py312-django{42,52,60},fido{11,20,21}
    py313-django{52,60}-fido{11,20,21}
    py314-django{52,60}-fido{11,20,21}

[testenv]
changedir=
    example/
deps =
    fido11: fido2>=1.1.0,<2.0
    fido20: fido2>=2.0.0,<2.1
    fido21: fido2>=2.1,<2.2
;    django20: django>=2.0,<2.1
;    django21: django>=2.1,<2.2
    django22: django>=2.2,<3.0
    django32: django>=3.2,<4.0
;    django40: django>=4.0,<4.1
;    django41: django>=4.1,<4.2
    django42: django>=4.2,<5.0
;    django50: django>=5.0,<5.1
;    django51: django>=5.1,<5.2
    django52: django>=5.2,<6.0
    django60: django>=6.0,<6.1
    ua-parser
    user-agents
    django-sslserver
    -rrequirements_test.txt

setenv =
    DJANGO_SETTINGS_MODULE = test_app.test_settings
allowlist_externals =
    coverage
commands =
    coverage run manage.py test

