# Generated by Django 5.2 on 2026-03-22 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkeys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasskey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='userpasskey',
            index=models.Index(fields=['credential_id', 'enabled'], name='passkeys_us_credent_3355ab_idx'),
        ),
    ]
