# Generated by Django 5.2 on 2026-03-22 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkeys', '0002_alter_userpasskey_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpasskey',
            options={'ordering': ['-added_on'], 'verbose_name': 'passkey', 'verbose_name_plural': 'passkeys'},
        ),
        migrations.AlterField(
            model_name='userpasskey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userpasskey',
            table='passkeys_userpasskey',
        ),
    ]
